config:
  join: "%player_displayname% &eist dem Spiel beigetreten."
  quit: "%player_displayname% &ehat das Spiel verlassen."
  kick: "%player_displayname% &r&ewurde gekickt. (&7%reason%&e)"
  ban: "&7%player% &r&ewurde gebannt. (&7%reason%&e)"
  ban-temp: "&7%player% &r&ewurde temporär gebannt. (&7%reason%&e)"
  pardon: "&7%player%&e wurde entbannt. (&7%reason%&e)"
  ban-ip: "&eIP-Adresse &7%ip% &r&ewurde gebannt. (&7%reason%&e)"
  ban-ip-temp: "&eIP-Adresse &7%ip% &r&ewurde temporär gebannt. (&7%reason%&e)"
  pardon-ip: "&eIP-Adresse &7%ip%&e wurde entbannt. (&7%reason%&e)"
  ban-screen: "&cGebannt.\n\nTyp: &7%type%\n&cZiel: &7%target%\n&cGrund: &7%reason%\n&cQuelle: &7%source%\n&cErstellt: &7%created%\n&cEnde: &7%expires%\n"
  whisper_sender: "&3Du an %target_player_displayname%&3: &r&f%message%"
  whisper_target: "&3%sender_player_displayname% &3an dich: &r&f%message%"
  chat: "%player_displayname%&r&f: "
  wiki: http://minecraft-de.gamepedia.com/
  map: http://example.com/
  map-worlds:
    - world
  map-name: flat
  map-zoom: 6
  map-y: 64
  navi-worlds:
    - world
  spawn: null
  motd1: "&aServer"
  motd2: "&7Server"
  whitelist-message: "&cNicht auf der Whitelist."
  plugin-prefix: ""